//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.03 at 01:49:33 PM MEZ 
//


package onepoint.project.tools.generated_warning;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the onepoint.project.tools.generated_warning package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Files_QNAME = new QName("", "files");
    private final static QName _OpResourceParameter_QNAME = new QName("", "parameter");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: onepoint.project.tools.generated_warning
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OpParameter }
     * 
     */
    public OpParameter createOpParameter() {
        return new OpParameter();
    }

    /**
     * Create an instance of {@link OpWarningFile }
     * 
     */
    public OpWarningFile createOpWarningFile() {
        return new OpWarningFile();
    }

    /**
     * Create an instance of {@link OpWarningFiles }
     * 
     */
    public OpWarningFiles createOpWarningFiles() {
        return new OpWarningFiles();
    }

    /**
     * Create an instance of {@link OpResource }
     * 
     */
    public OpResource createOpResource() {
        return new OpResource();
    }

    /**
     * Create an instance of {@link OpResourceMap }
     * 
     */
    public OpResourceMap createOpResourceMap() {
        return new OpResourceMap();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpWarningFiles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "files")
    public JAXBElement<OpWarningFiles> createFiles(OpWarningFiles value) {
        return new JAXBElement<OpWarningFiles>(_Files_QNAME, OpWarningFiles.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpParameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parameter", scope = OpResource.class)
    public JAXBElement<OpParameter> createOpResourceParameter(OpParameter value) {
        return new JAXBElement<OpParameter>(_OpResourceParameter_QNAME, OpParameter.class, OpResource.class, value);
    }

}
